# Generated by Django 4.0.3 on 2022-03-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.URLField()),
                ('repo', models.CharField(max_length=255, null=True)),
                ('about', models.CharField(max_length=255, null=True)),
                ('website_link', models.CharField(max_length=255, null=True)),
                ('stars', models.IntegerField(null=True)),
                ('forks', models.IntegerField(null=True)),
                ('watching', models.CharField(max_length=255, null=True)),
                ('main_branch_commit_count', models.IntegerField(null=True)),
                ('main_branch_latest_commit_author', models.CharField(max_length=255, null=True)),
                ('main_branch_latest_commit_datetime', models.DateTimeField(null=True)),
                ('main_branch_latest_commit_message', models.TextField(null=True)),
                ('release_count', models.IntegerField(null=True)),
                ('latest_release_tag', models.CharField(max_length=255, null=True)),
                ('latest_release_datetime', models.DateTimeField(null=True)),
                ('latest_release_changelog', models.TextField(null=True)),
            ],
        ),
    ]
